name: CI workflow

on:
  pull_request:
    branches: '**'
  workflow_dispatch:

env:
  APPLICATION_FOLDER: ~/game-lobby/frontend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/.next

      - name: Bundle Watch
        shell: bash
        env: 
          CI_REPO_OWNER: Game-as-a-Service
          CI_REPO_NAME: Game-Lobby-Web
          CI_BRANCH: ${{ github.head_ref }}
          CI_BRANCH_BASE: ${{ github.base_ref }}
          CI_COMMIT_SHA: ${{ github.sha }}
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: yarn run bundlewatch
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
            
      - name: Test
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        
      - name: lint
        run: npx eslint@7.32.0 --no-error-on-unmatched-pattern -c .eslintrc.json $(git diff --name-only --relative --diff-filter=ACMRTUXB HEAD~1 | grep  -E ".(js|jsx|ts|tsx)$")
  
  knip-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        
      - name: knip
        env: 
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          yarn run knip > knipScanResult.txt 2>&1
          node ./scripts/knipScanReporter.js

  lhci-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: run lighthouse-ci
        env:
            LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
            NEXT_PUBLIC_MOCK: true
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun || echo "LHCI failed!"

