name: CI workflow

on:
  pull_request:
    branches: '**'
  workflow_dispatch:

env:
  APPLICATION_FOLDER: ~/game-lobby/frontend

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with: 
          path: |
            node_modules
            ~/.cache/Cypress
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

